name: three16
favicon: null
layout_spectrum: 0.5369831384159625
typography_spectrum: 0.20888621360063553
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.27239459147676826
  lightness: 0.8140319704543799
  saturation: 0.4631915728095919
  rhythmicContrast: 0.46590885636396706
purpose: []
